apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd-a
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_YOUR_GIT_REPO_URL
    targetRevision: HEAD
    path: Argo/argocd-migration/app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

